### ISSUE TITLE
Libfuzz-parser memory leaks

### ISSUE THREAD

**Issue by tobhe** [openiked/openiked-portable#35]
The Libfuzz-parser test reports a number of leaks in `ikev2_pld_parse()`:
```Direct leak of 64 byte(s) in 1 object(s) allocated from:
    #0 0x4cdf82 in calloc (/home/runner/work/openiked-portable/openiked-portable/build/regress/parser-libfuzzer/test_libfuzzer+0x4cdf82)
    #1 0x504747 in ibuf_open (/home/runner/work/openiked-portable/openiked-portable/build/regress/parser-libfuzzer/test_libfuzzer+0x504747)
    #2 0x50479d in ibuf_dynamic (/home/runner/work/openiked-portable/openiked-portable/build/regress/parser-libfuzzer/test_libfuzzer+0x50479d)
    #3 0x501b86 in ibuf_new (/home/runner/work/openiked-portable/openiked-portable/build/regress/parser-libfuzzer/test_libfuzzer+0x501b86)
    #4 0x5001c8 in ikev2_pld_delete (/home/runner/work/openiked-portable/openiked-portable/build/regress/parser-libfuzzer/test_libfuzzer+0x5001c8)
    #5 0x500e69 in ikev2_pld_payloads (/home/runner/work/openiked-portable/openiked-portable/build/regress/parser-libfuzzer/test_libfuzzer+0x500e69)
```
The reason is that the fuzzing harness does not call `ikev2_msg_cleanup()`. However, getting `ikev2_msg_cleanup()` to compile and link with the test is not trivial because of symbol conflicts with `common.c`.

**Comment by tobhe** [comment]
Looks like leak errors can be disabled with `ASAN_OPTIONS=detect_leaks=0`.
Temporary fix in #51.
